# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - ${HOME_DIR}/cookie:/data
      # config
      - ${JUPYTERHUB_CONFIG}:/srv/jupyterhub/jupyterhub_config.py
      # user & image list
      - ${USER_LIST}:/srv/jupyterhub/config.yaml
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # proxy
      CONFIGPROXY_AUTH_TOKEN: ${CONFIGPROXY_AUTH_TOKEN}
      JHUB_DIR: ${JHUB_DIR}
      HOME_DIR: ${HOME_DIR}
      HOSTNODE: ${HOSTNAME}
      CONFIG_RUNNING: ${CONFIG_RUNNING}
    env_file:
      - ${OAUTH}
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
