FROM jupyter-minimal

ARG RELEASE_TAG=v1.63.2
ARG arch=x64
ARG OPENVSCODE_SERVER_ROOT=/opt/openvscode

user root
RUN wget https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-${RELEASE_TAG}/openvscode-server-${RELEASE_TAG}-linux-${arch}.tar.gz && \
    tar -xzf openvscode-server-${RELEASE_TAG}-linux-${arch}.tar.gz && \
    mv -f openvscode-server-${RELEASE_TAG}-linux-${arch} ${OPENVSCODE_SERVER_ROOT} && \
    rm -f openvscode-server-${RELEASE_TAG}-linux-${arch}.tar.gz
user $NB_USER

ENV PATH=${PATH}:${OPENVSCODE_SERVER_ROOT}

RUN conda install -c conda-forge \
    jupyter-server-proxy \
 && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

COPY --chown=1000:100 srv/jupyter_openvscode_proxy /tmp/jupyter_openvscode_proxy
RUN pip3 install --no-cache-dir  /tmp/jupyter_openvscode_proxy \
 && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

