FROM cschranz/gpu-jupyter:v1.4_cuda-11.0_ubuntu-20.04

# jupyterhub: last version from github
#RUN cd /tmp && git clone https://github.com/jupyterhub/jupyterhub && pip install /tmp/jupyterhub && rm -rf /tmp/jupyterhub

USER root

RUN conda update -n base conda
RUN conda update -c conda-forge -y notebook jupyterhub jupyterlab ipywidgets

RUN conda install -c conda-forge \
    jupyter-server-proxy \
    jupyter-rsession-proxy \
    imagemagick \
    openslide openslide-python flask
    
RUN jupyter labextension install jupyterlab-plotly @jupyter-widgets/jupyterlab-manager plotlywidget @ijmbarr/jupyterlab_spellchecker

# RUN pip3 install --no-cache-dir openslide-python

# rstudio
RUN apt-get update && apt-get -y --no-install-recommends install \
    file \
    git \
    libapparmor1 \
    libgc1c2 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    lsb-release \
    psmisc \
    procps \
    python-setuptools \
    sudo \
    wget \
    mc \
    && apt-get clean && rm -rf /var/lib/apt/lists


# code-server
RUN conda install -c conda-forge code-server

USER $NB_USER


RUN pip3 install jupyterlab-logout

COPY srv /srv

RUN pip3 install --upgrade pip  
RUN cp -r /srv /tmp/srv \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_tensorboard_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_deepzoom_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyterlab-control \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_via_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_codeserver_proxy \
 && rm -rf /tmp/srv \
 && chmod +w /opt/conda/

# radiomics
RUN conda install -c conda-forge pydicom && \
    pip3 install --no-cache-dir pyradiomics


# RUN pip3 install --no-cache-dir /srv/jupyter_deepzoom_proxy \
#  && pip3 install --no-cache-dir /srv/jupyter_tensorboard_proxy \
#  && pip3 install --no-cache-dir /srv/jupyter_via_proxy \
# # && pip3 install --no-cache-dir /srv/jupyter_codeserver_proxy \
#  && chmod g+w /opt/conda/share/jupyter/lab/extensions \
# # && rm -rf /srv/jupyter*_proxy \
#  && echo

ENV BASH_ENV ~/.bashrc
SHELL ["/bin/bash", "-c"]

# RUN conda create -y -n py2 python=2.7 \
#  && conda init \
#  && source /opt/conda/etc/profile.d/conda.sh && source /home/jovyan/.bashrc \
#  && conda activate py2 \
#  && conda install -c conda-forge ipykernel \
#  && pip install backports.functools-lru-cache \
#  && python -m ipykernel install --name py2 --display-name "Python 2.7" \
#  && conda install -c anaconda tensorflow-gpu=1.7.0 matplotlib h5py numba pandas \
#  && conda deactivate

COPY nvtop /usr/local/bin/nvtop


ENV START=/lab

ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

ENV RSESSION_PROXY_RSTUDIO_1_4=yes

#ENV RSTUDIO_VERSION=1.4.1106 not working
#ENV RSTUDIO_VERSION=1.3.1093 not working
ENV RSTUDIO_VERSION=1.3.959
# ENV RSTUDIO_VERSION=2021.09.0-351
ENV RSTUDIO_VERSION=1.4.1722
ENV LINUX=bionic
# xenial: ubuntu 16  bionic: ubuntu 18/20

# wget https://download2.rstudio.org/server/${LINUX}/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
USER root
COPY rstudio/${LINUX}/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
RUN cd /tmp \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && echo "USER=jovyan" >> /etc/environment \
    && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
    && cd $cwd
RUN cd /tmp && git clone https://github.com/jupyterhub/jupyter-rsession-proxy && cd jupyter-rsession-proxy && pip3 install .
RUN 
USER $NB_USER
