FROM base-notebook

# FROM cschranz/gpu-jupyter:latest

# RUN conda install -c conda-forge -y \
#     'jupyterhub=1.4.2' \
#     'ipywidgets=7.6.5'

# RUN conda install -c conda-forge \
#     jupyter-server-proxy \
#     jupyter-rsession-proxy \
#     imagemagick \
#     openslide openslide-python flask
    
# # rstudio
# USER root
# RUN apt-get update && apt-get -y --no-install-recommends install \
#     file \
#     git \
#     libapparmor1 \
#     libgc1c2 \
#     libclang-dev \
#     libcurl4-openssl-dev \
#     libedit2 \
#     libobjc4 \
#     libssl-dev \
#     libpq5 \
#     lsb-release \
#     psmisc \
#     procps \
#     python-setuptools \
#     sudo \
#     wget \
#     mc \
#     && apt-get clean && rm -rf /var/lib/apt/lists

# #ENV RSTUDIO_VERSION=1.4.1106 not working
# ENV RSTUDIO_VERSION=1.3.959
# ENV LINUX=bionic
# # xenial: ubuntu 16  bionic: ubuntu 18/20

# # wget https://download2.rstudio.org/server/${LINUX}/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \

# COPY rstudio/${LINUX}/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
# RUN cd /tmp \
#     && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
#     && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
#     && echo "USER=jovyan" >> /etc/environment \
#     && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
#     && cd $cwd

# USER $NB_USER

# # code-server
# RUN conda install -c conda-forge code-server


# # COPY srv/jupyterlab-logout /srv/jupyterlab-logout
# # RUN cp -r /srv/jupyterlab-logout /tmp/jupyterlab-logout && \
# #     pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/jupyterlab-logout && \
# #     rm -rf /tmp/jupyterlab-logout

# COPY srv /srv
# RUN pip3 install --upgrade pip  

# RUN cp -r /srv /tmp/srv \
#  && pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/jupyterlab-logout && \
#  && pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/srv/jupyter_tensorboard_proxy \
#  && pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/srv/jupyter_deepzoom_proxy \
#  && pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/srv/jupyterlab-control \
#  && pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/srv/jupyter_via_proxy \
#  && pip3 install --no-cache-dir --use-feature=in-tree-build /tmp/srv/jupyter_codeserver_proxy \
#  && rm -rf /tmp/srv \
#  && chmod +w /opt/conda/

# # radiomics
# RUN conda install -c conda-forge pydicom && \
#     pip3 install --no-cache-dir pyradiomics

# # torch
# RUN pip install --no-cache-dir torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html 
# # && \
# #     fix-permissions "${CONDA_DIR}" && \
# #     fix-permissions "/home/${NB_USER}"

# ENV BASH_ENV ~/.bashrc
# SHELL ["/bin/bash", "-c"]

# COPY nvtop /usr/local/bin/nvtop

# ENV START=/lab

# COPY srv/docker-entrypoint.sh /srv/docker-entrypoint.sh
# ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
# CMD ["start-singleuser.sh"]
