FROM jupyter-nvidia

USER $NB_UID

RUN conda install -c conda-forge \
    imagemagick \
    openslide openslide-python flask

COPY --chown=1000:100 srv /tmp/srv
# USER root
# RUN chown -R 1000:100 /tmp/srv
# USER $NB_UID

RUN echo - \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_tensorboard_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_deepzoom_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyterlab-control \
 && rm -rf /tmp/srv

COPY srv/docker-entrypoint.sh /srv/docker-entrypoint.sh
ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

