FROM jupyter-cuda

USER $NB_UID

RUN conda install -c conda-forge \
    jupyter-server-proxy \
    imagemagick \
    openslide openslide-python flask

RUN pip3 install jupyterlab-logout

RUN pip install --upgrade pip 

COPY srv /srv

RUN cp -r /srv /tmp/srv \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_tensorboard_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_deepzoom_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyterlab-control \
 && rm -rf /tmp/srv

ENV START=/lab

ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

