FROM jupyter/r-notebook:latest

# ARG JUPYTERHUB_VERSION
# RUN   python3 -m pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION

# jupyterhub: last version from github
RUN cd /tmp && git clone https://github.com/jupyterhub/jupyterhub && pip install /tmp/jupyterhub && rm -rf /tmp/jupyterhub

RUN conda install -c conda-forge \
    jupyter-server-proxy \
    jupyter-rsession-proxy \
    bash \
    nano \
    git \
    wget
    
# && jupyter labextension install @jupyterlab/server-proxy 

USER root

# rstudio
RUN apt-get update && apt-get -y --no-install-recommends install \
    file \
    libapparmor1 \
    libgc1c2 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    lsb-release \
    psmisc \
    procps \
    python-setuptools \
    sudo \
    && apt-get clean && rm -rf /var/lib/apt/lists

#ENV RSTUDIO_VERSION=1.4.1106 not working
ARG RSTUDIO_VERSION=1.3.959
ARG LINUX=bionic
# xenial: ubuntu 16  bionic: ubuntu 18/20

# wget https://download2.rstudio.org/server/${LINUX}/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \

COPY rstudio/${LINUX}/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
RUN cd /tmp \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && echo "USER=jovyan" >> /etc/environment \
    && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
    && cd $cwd

USER $NB_USER

ENV START=/rstudio

COPY srv /srv

USER root

ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

