FROM jupyter/datascience-notebook:lab-3.0.14
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#core-stacks
# https://hub.docker.com/r/jupyter/datascience-notebook/tags/?page=1&ordering=last_updated

#ARG JUPYTERHUB_VERSION
#RUN python3 -m pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION

# jupyterhub: last version from github
# RUN cd /tmp && git clone https://github.com/jupyterhub/jupyterhub && pip install /tmp/jupyterhub && rm -rf /tmp/jupyterhub

RUN conda update -n base conda
RUN conda install -c conda-forge \
    jupyter-server-proxy \
    jupyter-rsession-proxy \
    imagemagick \
    openslide flask \
    bash \
    nano \
    git \
    wget

RUN pip3 install --no-cache-dir openslide-python

# rstudio
USER root

RUN apt-get update && apt-get -y --no-install-recommends install \
    file \
    libapparmor1 \
    libgc1c2 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    lsb-release \
    psmisc \
    procps \
    python-setuptools \
    sudo \
    mc\
    && apt-get clean && rm -rf /var/lib/apt/lists

#    git \
#    wget \

#ENV RSTUDIO_VERSION=1.4.1106 not working
ENV RSTUDIO_VERSION=1.3.959
ENV LINUX=bionic
# xenial: ubuntu 16  bionic: ubuntu 18/20

# wget https://download2.rstudio.org/server/${LINUX}/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \

COPY rstudio/${LINUX}/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
RUN cd /tmp \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && echo "USER=jovyan" >> /etc/environment \
    && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
    && cd $cwd


COPY srv /srv

RUN chown -R 1001:100 /srv && chmod -R 775 /srv

USER jovyan

RUN pip3 install --use-feature=in-tree-build /srv/jupyter_deepzoom_proxy \
 && pip3 install --use-feature=in-tree-build /srv/jupyter_tensorboard_proxy \
# && pip3 install --no-cache-dir /srv/jupyter_codeserver_proxy \
# && chmod g+w /opt/conda/share/jupyter/lab/extensions \
 && echo

##### python 2.7
# RUN conda create -y -n py2 python=2.7 \
#  && conda init \
#  && source /opt/conda/etc/profile.d/conda.sh && source /home/jovyan/.bashrc \
#  && conda activate py2 \
#  && conda install -c conda-forge ipykernel \
#  && pip install backports.functools-lru-cache \
#  && python -m ipykernel install --name py2 --display-name "Python 2.7" \
#  && conda install -c anaconda matplotlib h5py numba pandas \
#  && conda deactivate


# code-server
RUN conda install -c conda-forge code-server \
 && pip3 install --no-cache-dir  --use-feature=in-tree-build /srv/jupyter_codeserver_proxy

RUN conda install -c conda-forge pydicom && \
    pip3 install --no-cache-dir pyradiomics

ENV BASH_ENV ~/.bashrc
SHELL ["/bin/bash", "-c"]

ENV START=/lab


ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]
