FROM cschranz/gpu-jupyter:v1.4_cuda-11.0_ubuntu-18.04

#ARG JUPYTERHUB_VERSION
#RUN python3 -m pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION

# jupyterhub: last version from github
RUN cd /tmp && git clone https://github.com/jupyterhub/jupyterhub && pip install /tmp/jupyterhub && rm -rf /tmp/jupyterhub

USER root
COPY nvtop /usr/local/bin/nvtop

# remove cuda-450
RUN rm /usr/lib/x86_64-linux-gnu/lib*.so.450.*

RUN conda install -c conda-forge \
    jupyter-server-proxy \
    jupyter-rsession-proxy \
    code-server \
    imagemagick \
    openslide flask \
    visdom 
    

RUN pip3 install --no-cache-dir openslide-python

# rstudio
RUN apt-get update && apt-get -y --no-install-recommends install \
    file \
    git \
    libapparmor1 \
    libgc1c2 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    lsb-release \
    psmisc \
    procps \
    python-setuptools \
    sudo \
    wget \
    mc\
    && apt-get clean && rm -rf /var/lib/apt/lists

#ENV RSTUDIO_VERSION=1.4.1106 not working
ENV RSTUDIO_VERSION=1.3.959
ENV LINUX=xenial
# xenial: ubuntu 16  bionic: ubuntu 18/20

# wget https://download2.rstudio.org/server/${LINUX}/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \

COPY rstudio/${LINUX}/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
RUN cd /tmp \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && echo "USER=jovyan" >> /etc/environment \
    && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
    && cd $cwd


COPY srv /srv

RUN pip3 install --no-cache-dir /srv/jupyter_codeserver_proxy \
 && pip3 install --no-cache-dir /srv/jupyter_deepzoom_proxy \
 && pip3 install --no-cache-dir /srv/jupyter_tensorboard_proxy \
 && chmod g+w /opt/conda/share/jupyter/lab/extensions \
 && rm -rf /srv/jupyter*_proxy

USER jovyan

ENV START=/lab

ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]
