FROM jupyter-minimal

USER $NB_USER

# javascript
RUN conda install -c conda-forge --yes gcc gxx make file binutils curl sed setuptools
USER root
RUN npm install -g npm@8.3.1 ijavascript && ijsinstall --install=global
USER $NB_USER