# jupyter-gpu (dl + r/rstudio + codeserver)

FROM jupyter-dl

# R pre-requisites
USER root

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    fonts-dejavu \
    unixodbc \
    unixodbc-dev \
    r-cran-rodbc \
    gfortran \
    gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Fix for devtools https://github.com/conda-forge/r-devtools-feedstock/issues/4
RUN ln -s /bin/tar /bin/gtar

USER $NB_USER

# R packages including IRKernel which gets installed globally.
ENV RVER=R4.1.2
RUN conda install --quiet --yes \
    'r-base=4.1.2' \
    'r-caret' \
    'r-crayon' \
    'r-devtools' \
    'r-forecast' \
    'r-hexbin' \
    'r-htmltools' \
    'r-htmlwidgets' \
    'r-irkernel' \
    'r-nycflights13' \
    'r-randomforest' \
    'r-rcurl' \
    'r-rmarkdown' \
    'r-rodbc' \
    'r-rsqlite' \
    'r-shiny' \
    'r-tidymodels' \
    'r-tidyverse' \
    'r-e1071' \
    'unixodbc' && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# rstudio
RUN conda install -c conda-forge \
    jupyter-server-proxy \
    bash \
    nano \
    git \
    wget \
    r-r.utils \
    && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

USER root

RUN apt-get update --yes && apt-get install --yes --no-install-recommends \
    file \
    libapparmor1 \
    libgc1c2 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    lsb-release \
    psmisc \
    procps \
    python-setuptools \
    sudo \
    openssh-client \
    && apt-get clean && rm -rf /var/lib/apt/lists

ARG RSTUDIO_VERSION=2021.09.1-372

COPY rstudio/bionic/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
RUN cd /tmp \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && echo "USER=$NB_USER" >> /etc/environment \
    && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
    && cd $cwd

USER $NB_USER

COPY --chown=1000:100 srv/jupyter-rsession-proxy /tmp/jupyter-rsession-proxy
RUN pip3 install --no-cache-dir /tmp/jupyter-rsession-proxy \
    && rm -rf /tmp/jupyter-rsession-proxy \
    && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

# code-server (conda not working, mamba: downgrades R)
COPY --chown=1000:100 srv/jupyter_codeserver_proxy /tmp/jupyter_codeserver_proxy
RUN pip3 install --no-cache-dir  /tmp/jupyter_codeserver_proxy \
 && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"
user root
RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --prefix=/usr/local
user $NB_USER

# monai
RUN mamba install --quiet --yes monai \
 && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"