# jupyter-dl (minimal + torch & Tensorflow deepzoom radiomics)

FROM jupyter-minimal

# Tensorflow (latest)
RUN pip install --quiet --no-cache-dir \
    tensorflow \
    && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

# & Torch (latest)
RUN conda install --quiet --yes \
    pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch && \
    conda clean --all -f -y \
    && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

# openslide
RUN mamba install -y \
    imagemagick \
    openslide openslide-python flask \
    && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

COPY --chown=1000:100 srv /tmp/srv

RUN echo - \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_tensorboard_proxy \
 && pip3 install --no-cache-dir /tmp/srv/jupyter_deepzoom_proxy \
 && rm -rf /tmp/srv \
 && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

# end

# radiomics (!! conda version requires python <=3.8)
# RUN conda install -c conda-forge -c radiomics pydicom pyradiomics \
#     && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

USER ${NB_UID}
ENV START=/lab

# new modules
# hiddenlayer https://github.com/waleedka/hiddenlayer
# torchinfo https://github.com/TylerYep/torchinfo
# pandarallel https://github.com/nalepae/pandarallel

RUN mamba install --quiet -y graphviz python-graphviz torchinfo \
    && pip3 install --quiet --no-cache-dir git+https://github.com/waleedka/hiddenlayer.git \
    && pip3 install --quiet --no-cache-dir pandarallel \
    && fix-permissions "${CONDA_DIR}" && fix-permissions "/home/${NB_USER}"

