FROM jupyter-rstudio

RUN conda install -c bioconda plink vcftools perl-vcftools-vcf bcftools p7zip r-r.utils bash

USER $NB_USER

ENV START=/rstudio

# ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
# CMD ["start-singleuser.sh"]
