FROM jupyter/datascience-notebook:lab-3.0.11
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#core-stacks
# https://hub.docker.com/r/jupyter/datascience-notebook/tags/?page=1&ordering=last_updated

#ARG JUPYTERHUB_VERSION
#RUN python3 -m pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION

# jupyterhub: last version from github
RUN cd /tmp && git clone https://github.com/jupyterhub/jupyterhub && pip install /tmp/jupyterhub && rm -rf /tmp/jupyterhub

USER root

RUN conda install -c conda-forge \
    jupyter-server-proxy \
    jupyter-rsession-proxy \
    code-server \
    imagemagick \
    openslide flask \
    visdom \
    nano \
    git \
    wget

# RUN conda install -c hcc midnight-commander

RUN pip3 install --no-cache-dir openslide-python

# rstudio
RUN apt-get update && apt-get -y --no-install-recommends install \
    file \
    libapparmor1 \
    libgc1c2 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    lsb-release \
    psmisc \
    procps \
    python-setuptools \
    sudo \
    mc\
    && apt-get clean && rm -rf /var/lib/apt/lists

#    git \
#    wget \

#ENV RSTUDIO_VERSION=1.4.1106 not working
ENV RSTUDIO_VERSION=1.3.959
ENV LINUX=bionic
# xenial: ubuntu 16  bionic: ubuntu 18/20

# wget https://download2.rstudio.org/server/${LINUX}/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \

COPY rstudio/${LINUX}/rstudio-server-${RSTUDIO_VERSION}-amd64.deb /tmp/
RUN cd /tmp \
    && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && rm rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
    && echo "USER=jovyan" >> /etc/environment \
    && echo -e "rsession-which-r=/opt/conda/lib/R\nrsession-ld-library-path=/opt/conda/lib:/opt/conda/x86_64-conda-linux-gnu/lib/" >> /etc/rstudio/rserver.conf \
    && cd $cwd


COPY srv /srv

RUN pip3 install --no-cache-dir /srv/jupyter_codeserver_proxy \
 && pip3 install --no-cache-dir /srv/jupyter_deepzoom_proxy \
 && pip3 install --no-cache-dir /srv/jupyter_tensorboard_proxy \
# && chmod g+w /opt/conda/share/jupyter/lab/extensions \
# && rm -rf /srv/jupyter*_proxy
 && echo

USER jovyan

ENV START=/lab

ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]
