FROM jamovi/jamovi:latest

# RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists
# RUN cd /tmp && git clone https://github.com/jupyterhub/jupyterhub && pip3 install /tmp/jupyterhub && rm -rf /tmp/jupyterhub

RUN apt-get install -y python3-pip && ln -s /usr/bin/python3 /usr/bin/python

#**
ARG HUB_VERSION
ENV HUB_VERSION=1.4.2
#**

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"
ARG NB_USER="jovyan"
ARG NB_UID="1000"
ARG NB_GID="100"

# Fix DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

RUN apt-get install --yes --no-install-recommends \
    tini \
    wget \
    ca-certificates \
    sudo \
    locales \
    fonts-liberation \
    nano \
    nodejs npm \
    run-one && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen 

# Configure environment
ENV SHELL=/bin/bash \
    NB_USER="${NB_USER}" \
    NB_UID=${NB_UID} \
    NB_GID=${NB_GID} \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

# Copy a script that we will use to correct permissions after running certain commands
COPY nvidia/fix-permissions /usr/local/bin/fix-permissions
RUN chmod a+rx /usr/local/bin/fix-permissions

# Enable prompt color in the skeleton .bashrc before creating the default NB_USER
# hadolint ignore=SC2016
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc

# Create NB_USER with name jovyan user with UID=1000 and in the 'users' group
# and make sure these dirs are writable by the `users` group.
RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su && \
    sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers && \
    sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers && \
    useradd -l -m -s /bin/bash -N -u "${NB_UID}" "${NB_USER}" && \
    chmod g+w /etc/passwd && \
    fix-permissions "${HOME}"

USER root
RUN /usr/bin/pip3 install setuptools wheel notebook jupyterhub==1.4.2 jupyterlab jupyter-server-proxy && \
    jupyter notebook --generate-config && \
    jupyter lab clean

EXPOSE 8888

# Copy local files as late as possible to avoid cache busting
COPY nvidia/start.sh nvidia/start-notebook.sh nvidia/start-singleuser.sh /usr/local/bin/
# Currently need to have both jupyter_notebook_config and jupyter_server_config to support classic and lab
COPY nvidia/jupyter_notebook_config.py /etc/jupyter/

# Fix permissions on /etc/jupyter as root
USER root

# Prepare upgrade to JupyterLab V3.0 #1205
RUN sed -re "s/c.NotebookApp/c.ServerApp/g" \
    /etc/jupyter/jupyter_notebook_config.py > /etc/jupyter/jupyter_server_config.py && \
    fix-permissions /etc/jupyter/

RUN chmod 755 /usr/local/bin/*

# modified to include control
COPY --chown=1000:100 srv/jupyterlab-logout /tmp/jupyterlab-logout
RUN pip3 install --no-cache-dir /tmp/jupyterlab-logout && \
    rm -rf /tmp/jupyterlab-logout \
    && fix-permissions "/home/${NB_USER}"

COPY --chown=1000:100 srv/jupyter_jamovi_proxy /tmp/jupyter_jamovi_proxy
RUN pip install --no-cache-dir /tmp/jupyter_jamovi_proxy && \
    rm -rf /tmp/jupyter_jamovi_proxy

# Switch to jovyan
ENV HOME="/home/${NB_USER}"
USER ${NB_UID}
RUN mkdir "/home/${NB_USER}/work" && \
    fix-permissions "/home/${NB_USER}"

WORKDIR /home/${NB_USER}
ENV START=/lab

COPY srv/setup/docker-entrypoint.sh /srv/docker-entrypoint.sh
ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]  

ENV LD_LIBRARY_PATH=/usr/local/lib/R/lib
ENV JAMOVI=1

# # -> /usr/bin/python3 -m jamovi.server 41337 --if=*
# # docker run -it --rm --user jovyan jupyter-jamovi bash

