- deepzoom:
    images_dir: /home/jovyan/images/U
    new_browser: True

- tensorboard:
    logdir: /home/jovyan/board
    new_browser: False

- codeserver:
    new_browser: False

- visdom:
    new_browser: True

